server:
  port: 8888  #设置端口号
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:mysql://104.129.184.206:3306/serverdemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      init-s-q-l: SET NAMES utf8mb4

    servlet:
      multipart:
        file-size-threshold:2KB
        max-file-size:200MB
        max-request-size:215MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.mic.table
  mapper-locations: classpath:/com/mic/mapper/*.xml
